import { Node as ReactFlowNode, Edge as ReactFlowEdge } from "@xyflow/react";
import { MindSpaceNodeData } from "./graph/transformer";

export function exportToMarkdown(
  title: string,
  nodes: ReactFlowNode[],
): string {
  let md = `# ${title}\n\n`;
  md += `*Generated by MindSpace AI Visual Note-Taking Platform*\n\n---\n\n`;

  nodes.forEach((n, idx) => {
    // SAFETY: React Flow node data conforms to MindSpaceNodeData
    const data = (n.data || {}) as unknown as MindSpaceNodeData;
    md += `## ${idx + 1}. ${data.label || "Node"}\n`;
    if (data.type) md += `**Type:** \`${data.type}\`  \n`;
    if (data.reminderAt)
      md += `**Reminder:** ${new Date(data.reminderAt).toLocaleString()}  \n`;
    if (data.markdown) md += `\n${data.markdown}\n\n`;
    md += `---\n\n`;
  });

  return md;
}

export function exportToJson(
  title: string,
  nodes: ReactFlowNode[],
  edges: ReactFlowEdge[],
): string {
  const exportData = {
    title,
    exportedAt: new Date().toISOString(),
    nodes: nodes.map((n) => ({
      id: n.id,
      position: n.position,
      data: n.data,
    })),
    edges: edges.map((e) => ({
      id: e.id,
      source: e.source,
      target: e.target,
      label: e.label,
    })),
  };

  return JSON.stringify(exportData, null, 2);
}

/**
 * Generates an SVG vector graphic representing the node graph
 */
export function exportToSvg(
  title: string,
  nodes: ReactFlowNode[],
  edges: ReactFlowEdge[],
): string {
  if (nodes.length === 0) {
    return `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><rect width="100%" height="100%" fill="#0A0A0A"/><text x="50%" y="50%" fill="#737373" text-anchor="middle" font-family="monospace">Empty MindSpace</text></svg>`;
  }

  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  const nodeWidth = 260;
  const nodeHeight = 120;

  nodes.forEach((n) => {
    minX = Math.min(minX, n.position.x);
    minY = Math.min(minY, n.position.y);
    maxX = Math.max(maxX, n.position.x + nodeWidth);
    maxY = Math.max(maxY, n.position.y + nodeHeight);
  });

  const padding = 80;
  const width = Math.max(800, maxX - minX + padding * 2);
  const height = Math.max(600, maxY - minY + padding * 2);
  const offsetX = -minX + padding;
  const offsetY = -minY + padding;

  const nodeMap = new Map<string, { x: number; y: number }>();
  nodes.forEach((n) => {
    nodeMap.set(n.id, { x: n.position.x + offsetX, y: n.position.y + offsetY });
  });

  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">\n`;
  svg += `<defs><style>
    .bg { fill: #0A0A0A; }
    .node-card { fill: #0F0F0F; stroke: #262626; stroke-width: 1.5; rx: 0; }
    .node-title { fill: #FAFAFA; font-family: 'Inter Tight', -apple-system, sans-serif; font-size: 15px; font-weight: bold; }
    .node-badge { fill: #737373; font-family: 'JetBrains Mono', monospace; font-size: 9px; text-transform: uppercase; }
    .edge-line { stroke: #FF3D00; stroke-width: 2; fill: none; }
    .edge-label { fill: #FF3D00; font-family: 'JetBrains Mono', monospace; font-size: 10px; }
    .graph-title { fill: #FAFAFA; font-family: 'Inter Tight', sans-serif; font-size: 20px; font-weight: 900; letter-spacing: -0.5px; }
  </style></defs>\n`;

  // Background
  svg += `<rect width="100%" height="100%" class="bg" />\n`;

  // Graph Header Title
  svg += `<text x="40" y="50" class="graph-title">${escapeXml(title.toUpperCase())}</text>\n`;

  // Draw Edges
  edges.forEach((e) => {
    const src = nodeMap.get(e.source);
    const tgt = nodeMap.get(e.target);
    if (!src || !tgt) return;

    const x1 = src.x + nodeWidth;
    const y1 = src.y + nodeHeight / 2;
    const x2 = tgt.x;
    const y2 = tgt.y + nodeHeight / 2;

    const dx = Math.abs(x2 - x1) * 0.5;
    const pathD = `M ${x1} ${y1} C ${x1 + dx} ${y1}, ${x2 - dx} ${y2}, ${x2} ${y2}`;

    svg += `<path d="${pathD}" class="edge-line" />\n`;
    if (e.label) {
      svg += `<text x="${(x1 + x2) / 2}" y="${(y1 + y2) / 2 - 6}" class="edge-label" text-anchor="middle">${escapeXml(String(e.label))}</text>\n`;
    }
  });

  // Draw Nodes
  nodes.forEach((n) => {
    const pos = nodeMap.get(n.id);
    if (!pos) return;
    // SAFETY: React Flow node data conforms to MindSpaceNodeData
    const data = (n.data || {}) as unknown as MindSpaceNodeData;
    const accent = data.color || "#FF3D00";
    const label = data.label || "Concept Node";

    svg += `<g transform="translate(${pos.x}, ${pos.y})">\n`;
    svg += `  <rect width="${nodeWidth}" height="${nodeHeight}" class="node-card" />\n`;
    svg += `  <rect width="48" height="4" fill="${accent}" />\n`;
    svg += `  <text x="14" y="28" class="node-badge">${escapeXml(data.type || "CONCEPT")}</text>\n`;
    svg += `  <text x="14" y="56" class="node-title">${escapeXml(label.slice(0, 24))}</text>\n`;
    if (data.markdown) {
      svg += `  <text x="14" y="82" fill="#737373" font-family="sans-serif" font-size="11">${escapeXml(data.markdown.slice(0, 36))}...</text>\n`;
    }
    svg += `</g>\n`;
  });

  svg += `</svg>`;
  return svg;
}

export function exportToPng(
  title: string,
  nodes: ReactFlowNode[],
  edges: ReactFlowEdge[],
) {
  const svgString = exportToSvg(title, nodes, edges);
  const blob = new Blob([svgString], { type: "image/svg+xml;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const img = new Image();

  img.onload = () => {
    const canvas = document.createElement("canvas");
    canvas.width = img.width * 2; // 2x high resolution
    canvas.height = img.height * 2;
    const ctx = canvas.getContext("2d");
    if (ctx) {
      ctx.scale(2, 2);
      ctx.drawImage(img, 0, 0);
      const pngUrl = canvas.toDataURL("image/png");
      const a = document.createElement("a");
      a.href = pngUrl;
      a.download = `${title.toLowerCase().replace(/\s+/g, "-") || "mindspace"}.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    }
    URL.revokeObjectURL(url);
  };

  img.src = url;
}

function escapeXml(unsafe: string): string {
  return unsafe.replace(/[<>&'"]/g, (c) => {
    switch (c) {
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case "&":
        return "&amp;";
      case "'":
        return "&apos;";
      case '"':
        return "&quot;";
      default:
        return c;
    }
  });
}

export function downloadFile(
  content: string,
  fileName: string,
  mimeType: string,
) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
