import { Node as ReactFlowNode, Edge as ReactFlowEdge } from '@xyflow/react';
import { MindSpaceNodeData } from './graph/transformer';

export function exportToMarkdown(title: string, nodes: ReactFlowNode[]): string {
  let md = `# ${title}\n\n`;
  md += `*Generated by MindSpace AI Visual Note-Taking Platform*\n\n---\n\n`;

  nodes.forEach((n, idx) => {
    const data = n.data as unknown as MindSpaceNodeData;
    md += `## ${idx + 1}. ${data.label}\n`;
    if (data.type) md += `**Type:** \`${data.type}\`  \n`;
    if (data.reminderAt) md += `**Reminder:** ${new Date(data.reminderAt).toLocaleString()}  \n`;
    if (data.markdown) md += `\n${data.markdown}\n\n`;
    md += `---\n\n`;
  });

  return md;
}

export function exportToJson(title: string, nodes: ReactFlowNode[], edges: ReactFlowEdge[]): string {
  const exportData = {
    title,
    exportedAt: new Date().toISOString(),
    nodes: nodes.map((n) => ({
      id: n.id,
      position: n.position,
      data: n.data,
    })),
    edges: edges.map((e) => ({
      id: e.id,
      source: e.source,
      target: e.target,
      label: e.label,
    })),
  };

  return JSON.stringify(exportData, null, 2);
}

export function downloadFile(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
