import { getStroke } from 'perfect-freehand';
import { VectorStroke, PointerPoint, PenSubtype } from './stylus-types';

/**
 * Returns perfect-freehand stroke options for realistic pen physics
 */
export function getPenFreehandOptions(
  subtype: PenSubtype,
  baseWidth: number,
  smoothingLevel: 'none' | 'mild' | 'high'
) {
  const streamline = smoothingLevel === 'high' ? 0.8 : smoothingLevel === 'mild' ? 0.5 : 0.15;

  if (subtype === 'fountain') {
    return {
      size: baseWidth * 1.8,
      thinning: 0.75, // Dynamic calligraphic width variation
      smoothing: 0.7,
      streamline,
      start: { taper: baseWidth * 1.5, cap: false },
      end: { taper: baseWidth * 1.5, cap: false },
      simulatePressure: false,
    };
  }

  if (subtype === 'pencil') {
    return {
      size: baseWidth * 1.2,
      thinning: 0.2, // Textured graphite, lower variation
      smoothing: 0.45,
      streamline,
      start: { taper: 0, cap: true },
      end: { taper: 0, cap: true },
      simulatePressure: false,
    };
  }

  // Ballpoint Pen (Default)
  return {
    size: baseWidth * 1.4,
    thinning: 0.45,
    smoothing: 0.55,
    streamline,
    start: { taper: baseWidth * 0.5, cap: true },
    end: { taper: baseWidth * 0.5, cap: true },
    simulatePressure: false,
  };
}

/**
 * Generates an SVG Path string (d attribute) from an array of PointerPoints
 */
export function getSvgPathFromPoints(
  points: PointerPoint[],
  subtype: PenSubtype,
  baseWidth: number,
  smoothing: 'none' | 'mild' | 'high'
): string {
  if (!points || points.length === 0) return '';

  const inputPoints = points.map((p) => [p.x, p.y, p.pressure > 0 ? p.pressure : 0.5]);
  const options = getPenFreehandOptions(subtype, baseWidth, smoothing);
  const strokeOutline = getStroke(inputPoints, options);

  return getSvgPathFromStrokeOutline(strokeOutline);
}

export function getSvgPathFromStrokeOutline(outlinePoints: number[][]): string {
  if (outlinePoints.length < 2) return '';

  const d = outlinePoints.reduce(
    (acc, [x0, y0], i, arr) => {
      const [x1, y1] = arr[(i + 1) % arr.length];
      return `${acc} ${x0.toFixed(1)},${y0.toFixed(1)} ${(x0 + x1) / 2},${(y0 + y1) / 2}`;
    },
    `M ${outlinePoints[0][0].toFixed(1)},${outlinePoints[0][1].toFixed(1)} Q`
  );

  return `${d} Z`;
}

/**
 * Renders vector stroke onto Canvas context, fully supporting Solid, Dashed, Dotted, Fountain Pen, Ballpoint, Pencil, and Highlighter
 */
export function renderStrokeOnCanvas(ctx: CanvasRenderingContext2D, stroke: VectorStroke) {
  const points = stroke.points;
  if (!points || points.length === 0) return;

  ctx.save();

  // 1. Check for Dashed or Dotted line types
  if (stroke.lineType === 'dashed' || stroke.lineType === 'dotted') {
    ctx.beginPath();
    ctx.strokeStyle = stroke.color;
    ctx.lineWidth = stroke.width;

    if (stroke.lineType === 'dashed') {
      ctx.setLineDash([stroke.width * 3, stroke.width * 2]);
    } else {
      ctx.setLineDash([stroke.width * 0.8, stroke.width * 1.5]);
      ctx.lineCap = 'round';
    }

    if (stroke.tool === 'highlighter') {
      ctx.globalCompositeOperation = 'source-over';
      ctx.strokeStyle = stroke.color + '66';
      ctx.lineWidth = stroke.width * 3;
    }

    ctx.moveTo(points[0].x, points[0].y);
    for (let i = 1; i < points.length; i++) {
      ctx.lineTo(points[i].x, points[i].y);
    }
    ctx.stroke();
    ctx.restore();
    return;
  }

  // 2. Solid Lines (Polygon Path generated by perfect-freehand)
  const svgPathData = getSvgPathFromPoints(stroke.points, stroke.penSubtype, stroke.width, stroke.smoothing);
  if (!svgPathData) {
    ctx.restore();
    return;
  }

  if (stroke.tool === 'highlighter') {
    ctx.globalCompositeOperation = 'source-over';
    ctx.fillStyle = stroke.color + '55'; // Translucent highlighter
  } else if (stroke.penSubtype === 'pencil') {
    ctx.globalCompositeOperation = 'source-over';
    ctx.globalAlpha = 0.7; // Graphite pencil texture opacity
    ctx.fillStyle = stroke.color;
  } else {
    ctx.globalCompositeOperation = 'source-over';
    ctx.globalAlpha = 1.0;
    ctx.fillStyle = stroke.color;
  }

  try {
    const path2d = new Path2D(svgPathData);
    ctx.fill(path2d);
  } catch {
    ctx.beginPath();
    ctx.moveTo(points[0].x, points[0].y);
    for (let i = 1; i < points.length; i++) {
      ctx.lineTo(points[i].x, points[i].y);
    }
    ctx.lineWidth = stroke.width;
    ctx.strokeStyle = stroke.color;
    ctx.stroke();
  }

  ctx.restore();
}
